module Obsidian
  module Import
    module Adapters
      class RubyGems < Base
        BASE_URL: String

        def search: (query: String) -> Array[Resource]

        def lookup: (id: String) -> Resource

        def normalize: (record: untyped) -> Resource

        private

        def authors: (String? value) -> Array[String]

        def base_url: () -> String
      end
    end
  end
end
